### ISSUE TITLE
Several formats for a data product

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/EPNTAP#10]
At line [221](https://github.com/ivoa-std/EPNTAP/blob/7c94296c0ad0890b96104d4695bc9e2997013057/EPNTAP.tex#L221) of current version, one can read: 
```
\item Only one data product is linked per table row, and parameters
in that row describe that product. The same data provided under two
different file formats must be described on two table rows.
```

There are two ways of doing this: 
- either having separate rows (as stated in the text) 
- or having a primary granule version (with a specific format), with other formats accessible through datalink. 

I propose to modify the text as follows:

```
\item Only one data product is linked per table row, and parameters
in that row describe that product. In case the same data product is 
distributed with several formats, there can be either as many rows 
as there are various formats, or there can be main data product (with
the preferred format), and other formats distributed through datalink.
```

**Comment by Erard** [comment]
OK in pinciple, I'll rewrite a bit
