### ISSUE TITLE
UCD

### ISSUE THREAD

**Issue by Erard** [ivoa-std/EPNTAP#2]
Apparenty an issue with em.freq;stat.interval;stat.min / max
(stat.interval should be last, as per http://cds.unistra.fr/UCD/tools.htx)
em.freq;spect.binSize;stat.min / max    looks better anyway

**Comment by mbtaylor** [comment]
I don't believe that `em.freq;stat.interval;stat.min`/`max` is illegal according to [UCD1+ 1.4](https://www.ivoa.net/Documents/UCD1+/); but if you prefer it changed that's fine.

**Comment by Erard** [comment]
It didn't pass the validation at CDS - invalid sequence of syntax codes (QSS)
I'm not quite sure about binSize in this context, but it doesn't clash with the definition

**Comment by mbtaylor** [comment]
Interesting, it passes the [Ucidy](https://github.com/gmantele/ucidy) validation.  @gmantele, are there syntax constraints in UCD1+ that are not tested by Ucidy?

**Comment by gmantele** [comment]
> Interesting, it passes the [Ucidy](https://github.com/gmantele/ucidy) validation. @gmantele, are there syntax constraints in UCD1+ that are not tested by Ucidy?

Strange. I checked the syntax codes of `em.freq` (Q, so can be Primary or Secondary), `stat.interval` (Secondary) and `stat.min` (Secondary) in UCD1+-1.3 and 1.4. Both versions agreed on these syntax codes. So, according to me what Ucidy returns is correct: `em.freq;stat.interval;stat.min` is a valid UCD.

I'll speak with the maintainers of http://cds.unistra.fr/UCD/tools.htx to see why our tools disagree on this one.

The only difference with `em.freq;spect.binSize;stat.min` is that `spect.binSize` is Q too. So, of course this one is also valid.
